### ISSUE TITLE
zaw run immediately after starting shell

### ISSUE THREAD

**Issue by NigoroJr** [b4b4r07/zplug2#10]
With the following `.zshrc`, I noticed zaw is run immediately after starting the shell.

``` zsh
source ~/.zplug/zplug

zplug 'zsh-users/zaw'

! zplug check && zplug install

zplug load --verbose
```

I have confirmed this under Gentoo Linux and Mac both running zsh 5.2.

This didn't happen before 5ae70bd2933756d01ff24b944d2aa46014cf6454, and as far as I can tell, it only happens for zaw. zaw keeps prompting even when I cancel it, so my guess is that it's something related to the `precmd` hook but I don't see anything apparent in the change.

**Comment by babarot** [comment]
Thank you for your report. Let me check.

**Comment by NigoroJr** [comment]
Fix confirmed, thanks!

Could you clarify a bit on what was happening?

**Comment by babarot** [comment]
OK.

Thanks to this line (https://github.com/b4b4r07/zplug2/commit/9fb327453618a0b295e7cbe46d12a83579c41d72#diff-266f6996ac92a23c674c5d269ef22b1fR218), this issue was fixed.

Before https://github.com/b4b4r07/zplug2/commit/5ae70bd2933756d01ff24b944d2aa46014cf6454, zplug narrow down the files the ending in `*.{plugin.zsh,zsh,zsh-theme}` (https://github.com/b4b4r07/zplug2/commit/5ae70bd2933756d01ff24b944d2aa46014cf6454#diff-266f6996ac92a23c674c5d269ef22b1fL165), but after 5ae70bd2933756d01ff24b944d2aa46014cf6454, zplug do the files ending in `*.zsh`. This ends up including `zaw-launcher.zsh`.

**Comment by NigoroJr** [comment]
Ah, I see now. Thank you for clarifying :bulb:
